<?php

namespace App\BusinessLogic\ImportExcel\Impl;


use App\Dao\Users\UserDao;
use App\Models\Acl\Role;
use App\User;
use Illuminate\Support\Facades\Log;
use PhpOffice\PhpSpreadsheet\IOFactory;

class UpdateTeacherPhone extends AbstractImporter
{
    protected $data;

    public function __construct()
    {

    }

    public function handle()
    {
        $userDao = new UserDao;
        $this->loadExcelFile();
        $sheetIndexArray = $this->getSheetIndexArray();
        $str = "文件数据格式有问题请重新上传, 第";
        foreach($sheetIndexArray as $sheetIndex) {
            echo '已拿到第'. ($sheetIndex+1).' sheet的数据 开始循环.....'.PHP_EOL;
            $sheetData = $this->getSheetData($sheetIndex);
            echo '开始检查文件格式是否正确'.PHP_EOL;
            // 检查文件格式是否正确
            foreach ($sheetData[0] as $key => $val) {
                if ($this->fileFormat()[$key] != $val) {
                    echo  $str. ($key+1) . "列应该是". $this->fileFormat()[$key];die;
                }
            }
            echo '检查文件格式正确 开始循环....'.PHP_EOL;
            unset($sheetData[0]); // 去掉文件头
            foreach ($sheetData as $key => $val) {
                $count = User::where(['name' => $val[0], 'type'=> Role::TEACHER])->count();
                $phone = $userDao->getUserByMobile($val[1]);
                // 判断是否只有一个用户, 姓名可能有重复的
                if ($count === 1 && is_null($phone)) {
                    // 只有一个的时候开始修改
                    $result = User::where(['name'=>$val[0], 'type'=> Role::TEACHER])->update(['mobile' => $val[1]]);
                    if ($result) {
                        echo $val[0].'----------修改成功'.PHP_EOL;
                    }
                } else {
                    if ($count > 1) {
                        echo $val[0]. "有两个用户 跳过此人".PHP_EOL;
                        Log::info($val[0].'---有两个用户');
                    } elseif($count == 0) {
                        echo $val[0]. "没有这个用户".PHP_EOL;
                        Log::info($val[0].'---没有这个用户');
                    }
                    else {
//                        echo $val[0]. "手机号已经被使用了 跳过此人".PHP_EOL;
//                        Log::info($val[0].'----'.$val[1].'---手机号已经被使用了');
                    }
                    continue;
                }
            }
        }
    }

    /**
     * 获取 excel 文件
     * @throws \PhpOffice\PhpSpreadsheet\Reader\Exception
     */
    public function loadExcelFile()
    {
        set_time_limit(0);
        ini_set('memory_limit', -1);
        $filePath =  'app/Console/Commands/data/lixian_teacher_phone.xls';
        $objReader = IOFactory::createReader('Xls');
        $objPHPExcel = $objReader->load($filePath);
        $worksheet = $objPHPExcel->getAllSheets();
        $this->data = $worksheet;
    }

    public function getSheetData($sheetIndex)
    {
        return parent::getSheetData($sheetIndex); // TODO: Change the autogenerated stub
    }


    /**
     * 文件格式标准
     */
    public function fileFormat()
    {
        return [
            "姓名",
            "手机号",
        ];
    }

}
